name: ci

on:
  - pull_request
  - push

jobs:
  tests:
    name: PHP-${{ matrix.php }}-composer:${{ matrix.composer }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php:
          - "8.1"
          - "8.2"

        composer:
          - "^2.0"
          - "dev-main"

    steps:
      - name: Configure git
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v2

      - name: Install composer
        run: composer require --dev "composer/composer:${{ matrix.composer }}" --update-with-dependencies

      - name: PHPUnit
        run: |
          vendor/bin/phpunit --verbose --colors=always
          cd tests/scripts && sh run.sh
